FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./src/celery/requirements.txt /code/

RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY ./src/celery/ /code/src/celery/
COPY ./src/config.py /code/src/
