FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY ./dev_requirements.txt /code/
RUN pip install --upgrade pip && pip install -r dev_requirements.txt

COPY . /code
